name: CD

on:
  push:
    tags:
      - "*"

concurrency:
  group: deployment-main
  cancel-in-progress: false

jobs:
  publish_openapi_client:
    name: Publishing OpenAPI Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.2
